### ISSUE TITLE
Aggregation functions should coerce to `MISSING` in permissive mode and not error

### ISSUE THREAD

**Issue by alancai98** [partiql/partiql-lang-kotlin#1036]
Relevant spec issue: https://github.com/partiql/partiql-spec/issues/50.

Aggregation functions such as `SUM` and `AVG` that expect numeric elements should coerce to `MISSING` in permissive typing mode and not error.

Current behavior:
```
-- v0.9.3 CLI run with experimental pipeline and permissive typing mode
❯ ./partiql-cli/build/install/partiql-cli/bin/partiql --pipeline=EXPERIMENTAL --typing-mode=PERMISSIVE
Welcome to the PartiQL shell!
Typing mode: PERMISSIVE
Using version: 0.9.3-SNAPSHOT-7e1ffd45
PartiQL> SELECT SUM(a) FROM <<{'a': 1}, {'a': 'non-numeric'}>> AS t;
==='
org.partiql.lang.eval.EvaluationException: Aggregate function SUM expects arguments of NUMBER type but the following value was provided: 'non-numeric', with type of STRING
	Evaluator Error: at line <UNKNOWN>, column <UNKNOWN>: Invalid arguments for agg function, <UNKNOWN> : <UNKNOWN>

	at org.partiql.lang.eval.ExceptionsKt.err(Exceptions.kt:59)
	at org.partiql.lang.eval.ExceptionsKt.errNoContext(Exceptions.kt:55)
	at org.partiql.lang.eval.physical.operators.AccumulatorKt.checkIsNumberType(Accumulator.kt:158)
	at org.partiql.lang.eval.physical.operators.AccumulatorSum.nextValue(Accumulator.kt:67)
	at org.partiql.lang.eval.physical.operators.Accumulator.next(Accumulator.kt:54)
	at org.partiql.lang.eval.physical.operators.AggregateOperatorDefault$evaluate$1.invokeSuspend(AggregateOperatorFactory.kt:91)
(Rest of error omitted)
```

```
-- v0.9.3 CLI run with default pipeline and permissive typing mode
❯ ./partiql-cli/build/install/partiql-cli/bin/partiql --typing-mode=PERMISSIVE
Welcome to the PartiQL shell!
Typing mode: PERMISSIVE
Using version: 0.9.3-SNAPSHOT-7e1ffd45
PartiQL> SELECT SUM(a) FROM <<{'a': 1}, {'a': 'non-numeric'}>> AS t;
Evaluator Error: at line 1, column 1: Invalid arguments for agg function, <UNKNOWN> : <UNKNOWN>
Aggregate function SUM expects arguments of NUMBER type but the following value was provided: 'non-numeric', with type of STRING
ERROR!
```

Similarly for the `COLL_*` functions:

```
-- v0.9.3 CLI run with experimental pipeline and permissive typing mode
PartiQL> COLL_SUM('distinct', [1, 2, 'non-numeric']);
Evaluator Error: at line 1, column 1: Invalid arguments for agg function, <UNKNOWN> : <UNKNOWN>
Aggregate function SUM expects arguments of NUMBER type but the following value was provided: 'non-numeric', with type of STRING
ERROR!
```

```
-- v0.9.3 CLI run with default pipeline and permissive typing mode
PartiQL> COLL_SUM('distinct', [1, 2, 'non-numeric']);
Evaluator Error: at line 1, column 1: Invalid arguments for agg function, <UNKNOWN> : <UNKNOWN>
Aggregate function SUM expects arguments of NUMBER type but the following value was provided: 'non-numeric', with type of STRING
ERROR!
```

We should also update the Kotlin implementation's documentation regarding aggregation functions: [Aggregate Functions.md](https://github.com/partiql/partiql-lang-kotlin/blob/1a9231ad74f70247bd2c3486357503db60c96da5/docs/wiki/documentation/Aggregate%20Functions.md).

**Comment by alancai98** [comment]
As a side note, the CLI exits for the query `SELECT SUM(a) FROM <<{'a': 1}, {'a': 'non-numeric'}>> AS t` when run with the experimental pipeline and permissive mode.

Related issue: https://github.com/partiql/partiql-lang-kotlin/issues/1029.
