### ISSUE TITLE
Year is not a valid identifier

### ISSUE THREAD

**Issue by almann** [partiql/partiql-lang-kotlin#121]
There appears to be interference in the lexer around `year` being treated as a non-identifier.  The unquoted form should be allowed.

```
PartiQL> SELECT x.year FROM <<`{year:1999}`>>
   | 
org.partiql.lang.syntax.ParserException: Invalid path dot component
	Parser Error: at line 1, column 10: Invalid path component, expecting either an IDENTIFIER or STAR, got: DATE_PART with value: 
"year"

	at org.partiql.lang.util.TokenListExtensionsKt.err(TokenListExtensions.kt:59)
	at org.partiql.lang.util.TokenListExtensionsKt.err(TokenListExtensions.kt:68)
	at org.partiql.lang.util.TokenListExtensionsKt.err$default(TokenListExtensions.kt:67)
	at org.partiql.lang.syntax.SqlParser.parsePathTerm(SqlParser.kt:808)
	at org.partiql.lang.syntax.SqlParser.parseUnaryTerm(SqlParser.kt:781)
	at org.partiql.lang.syntax.SqlParser.parseExpression$lang(SqlParser.kt:668)
	at org.partiql.lang.syntax.SqlParser.parseExpression$lang$default(SqlParser.kt:667)
	at org.partiql.lang.syntax.SqlParser.parseSelectList(SqlParser.kt:1126)
	at org.partiql.lang.syntax.SqlParser.parseSelect(SqlParser.kt:1023)
	at org.partiql.lang.syntax.SqlParser.parseTerm(SqlParser.kt:855)
	at org.partiql.lang.syntax.SqlParser.parsePathTerm(SqlParser.kt:785)
	at org.partiql.lang.syntax.SqlParser.parseUnaryTerm(SqlParser.kt:781)
	at org.partiql.lang.syntax.SqlParser.parseExpression$lang(SqlParser.kt:668)
	at org.partiql.lang.syntax.SqlParser.parseExpression$lang$default(SqlParser.kt:667)
	at org.partiql.lang.syntax.SqlParser.parseExprNode(SqlParser.kt:1594)
	at org.partiql.lang.CompilerPipelineImpl.compile(CompilerPipeline.kt:164)
	at org.partiql.cli.Repl$executePartiQL$1.invoke(Repl.kt:237)
	at org.partiql.cli.Repl$executePartiQL$1.invoke(Repl.kt:105)
	at org.partiql.cli.Repl$executeTemplate$totalMs$1.invoke(Repl.kt:208)
	at org.partiql.cli.Repl$executeTemplate$totalMs$1.invoke(Repl.kt:105)
	at org.partiql.cli.Timer$DefaultImpls.timeIt(Repl.kt:95)
	at org.partiql.cli.Repl$1.timeIt(Repl.kt:111)
	at org.partiql.cli.Repl.executeTemplate(Repl.kt:207)
	at org.partiql.cli.Repl.executePartiQL(Repl.kt:233)
	at org.partiql.cli.Repl.run(Repl.kt:300)
	at org.partiql.cli.Main.runRepl(main.kt:154)
	at org.partiql.cli.Main.main(main.kt:139)
ERROR!
```

**Comment by raganhan** [comment]
`year` is a [sql92 keyword](https://ronsavage.github.io/SQL/sql-92.bnf.html#key%20word). IIRC you have to double quote any keyword to use them as identifiers

**Comment by almann** [comment]
This came up because the this works in a bunch of database vendors, where I think we are following the letter of the law.

Section 5.2 of SQL-92 does say:
```
         11)The <identifier body> of a <regular identifier> (with every
            letter that is a lower-case letter replaced by the equivalent
            upper-case letter or letters), treated as the repetition of
            a <character string literal> that specifies a <character set
            specification> of SQL_TEXT, shall not be equal, according to
            the comparison rules in Subclause 8.2, "<comparison predicate>",
            to any <reserved word> (with every letter that is a lower-case
            letter replaced by the equivalent upper-case letter or letters),
            treated as the repetition of a <character string literal> that
            specifies a <character set specification> of SQL_TEXT.

            Note: It is the intention that no <key word> specified in this
            International Standard or revisions thereto shall end with an
            <underscore>.
```

**Comment by almann** [comment]
I need to investigate if the other vendors have some context sensitivity here, to make common keywords behave as identifiers.

**Comment by almann** [comment]
Interesting, [Postgres], [SQL Server][sql-server], and [Oracle] all go out of there way to make some of these SQL reserved words as un-reserved.  I think we should be somewhat pragmatic here and consider the conservative cases of keywords that can be used as identifiers.

[postgres]: https://www.postgresql.org/docs/current/sql-keywords-appendix.html
[sql-server]: https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-2017
[oracle]: https://docs.oracle.com/cd/B10501_01/appdev.920/a42525/apb.htm

**Comment by almann** [comment]
Opened partiql/partiql-spec#2 to track the broader issue more formally.

**Comment by raganhan** [comment]
Other vendors are not limited to SQL92 and later revisions dropped some keywords, `year` being one of them. 

Agreed that being pragmatic here is more important to avoid surprises so I'am all for treating `year` as a keyword contextually. That being said partiql/partiql-spec#2 should be done first before we implement anything to avoid unintended consequences
