### ISSUE TITLE
Cannot use group by with 2 level nested values

### ISSUE THREAD

**Issue by mustafaakin** [partiql/partiql-lang-kotlin#458]
I can safely run the following query:

    SELECT count(1), x.y FROM mydata GROUP BY x.y

However the following does not run.

    SELECT count(1), x.z.t FROM mydata GROUP BY x.z.t

Fails with the following message:

```
Exception in thread "main" org.partiql.lang.eval.EvaluationException: No such binding: x
	Evaluator Error: at line 1, column 18: Binding 'x' does not exist
```

Read the language spec and tutorial, and I'm puzzled on what to do. 

The full code for reference is attached:

```kotlin
import com.amazon.ion.system.IonSystemBuilder
import org.partiql.lang.CompilerPipeline
import org.partiql.lang.eval.Bindings
import org.partiql.lang.eval.EvaluationSession
import org.partiql.lang.eval.ExprValue

fun main() {
  val ion = IonSystemBuilder.standard().build()
  val pipeline = CompilerPipeline.standard(ion)

  val data = """
    {
      "name": "mustafa",
      "x": {
        "y": "123",
        "z": {
          "t": "456"
        }
      }
    }
  """.trimIndent()

  val globalVariables = Bindings.buildLazyBindings<ExprValue> {
    addBinding("mydata") {
      val value = ion.loader.load(data)
      pipeline.valueFactory.newFromIonValue(value)
    }
  }

  val queries = listOf(
    "SELECT * FROM mydata",
    "SELECT name, x.y FROM mydata",
    "SELECT name, x.y, x.z.t FROM mydata",
    "SELECT count(1) FROM mydata",
    "SELECT count(1), name FROM mydata GROUP BY name",
    "SELECT count(1), x FROM mydata GROUP BY x",
    "SELECT count(1), x.y FROM mydata GROUP BY x.y",
    "SELECT count(1), x.z FROM mydata GROUP BY x.z  ",
    "SELECT count(1), x.z.t FROM mydata GROUP BY x.z.t",
  )

  for (query in queries) {
    println("Executing $query")
    val session = EvaluationSession.build { globals(globalVariables) }
    val result = pipeline.compile(query).eval(session)
    println(result)
  }
}
```

Output is:

```
Executing SELECT * FROM mydata
<<{'name': 'mustafa', 'x': {'y': '123', 'z': {'t': '456'}}}>>
Executing SELECT name, x.y FROM mydata
<<{'name': 'mustafa', 'y': '123'}>>
Executing SELECT name, x.y, x.z.t FROM mydata
<<{'name': 'mustafa', 'y': '123', 't': '456'}>>
Executing SELECT count(1) FROM mydata
<<{'_1': 1}>>
Executing SELECT count(1), name FROM mydata GROUP BY name
<<{'_1': 1, 'name': 'mustafa'}>>
Executing SELECT count(1), x FROM mydata GROUP BY x
<<{'_1': 1, 'x': {'y': '123', 'z': {'t': '456'}}}>>
Executing SELECT count(1), x.y FROM mydata GROUP BY x.y
<<{'_1': 1, 'y': '123'}>>
Executing SELECT count(1), x.z FROM mydata GROUP BY x.z  
<<{'_1': 1, 'z': {'t': '456'}}>>
Executing SELECT count(1), x.z.t FROM mydata GROUP BY x.z.t
Exception in thread "main" org.partiql.lang.eval.EvaluationException: No such binding: x
	Evaluator Error: at line 1, column 18: Binding 'x' does not exist

	at org.partiql.lang.eval.EvaluatingCompiler$compileVariableReference$$inlined$thunkEnv$lang$1.invoke(Thunk.kt:295)
	at org.partiql.lang.eval.EvaluatingCompiler$compileVariableReference$$inlined$thunkEnv$lang$1.invoke(Thunk.kt:100)
	at org.partiql.lang.eval.EvaluatingCompiler$compilePath$$inlined$thunkEnv$lang$1.invoke(Thunk.kt:283)
	at org.partiql.lang.eval.EvaluatingCompiler$compilePath$$inlined$thunkEnv$lang$1.invoke(Thunk.kt:100)
	at org.partiql.lang.eval.EvaluatingCompiler$compileSelect$2$4$$special$$inlined$thunkEnvValue$lang$1.invoke(Thunk.kt:287)
	at org.partiql.lang.eval.EvaluatingCompiler$compileSelect$2$4$$special$$inlined$thunkEnvValue$lang$1.invoke(Thunk.kt:100)
	at org.partiql.lang.eval.EvaluatingCompiler$createFilterHavingAndProjectClosure$2.invoke(EvaluatingCompiler.kt:1331)
	at org.partiql.lang.eval.EvaluatingCompiler$createFilterHavingAndProjectClosure$2.invoke(EvaluatingCompiler.kt:57)
	at org.partiql.lang.eval.EvaluatingCompiler$compileSelect$2$1$getQueryThunk$$inlined$thunkEnv$lang$3.invoke(Thunk.kt:334)
	at org.partiql.lang.eval.EvaluatingCompiler$compileSelect$2$1$getQueryThunk$$inlined$thunkEnv$lang$3.invoke(Thunk.kt:100)
	at org.partiql.lang.eval.EvaluatingCompiler$compileSelect$2$1$getQueryThunk$$inlined$thunkEnv$lang$4.invoke(Thunk.kt:283)
	at org.partiql.lang.eval.EvaluatingCompiler$compileSelect$2$1$getQueryThunk$$inlined$thunkEnv$lang$4.invoke(Thunk.kt:100)
	at org.partiql.lang.eval.EvaluatingCompiler$compile$1.eval(EvaluatingCompiler.kt:234)
	at com.mustafa.PartiTestKt.main(PartiTest.kt:49)
	at com.mustafa.PartiTestKt.main(PartiTest.kt)
```

**Comment by mustafaakin** [comment]
After submitting the question, I found out that the following works:

```sql
SELECT count(1), wow FROM mydata GROUP BY x.z.t AS wow
<<{'_1': 1, 'wow': '456'}>>
```

But why the first one does not work? I'm trying to have a deeper understanding on how the implementation works.
