### ISSUE TITLE
Unexpected/incorrect exception thrown by StaticTypeInferenceVisitorTransform when calling a function with a struct reference of the wrong type

### ISSUE THREAD

**Issue by lziq** [partiql/partiql-lang-kotlin#526]
When I call StaticTypeInferenceVisitorTransform.transformStatement() on a query calling a function where I am passing in a field of a struct of the wrong type, I expect to get a SemanticException indicating "InvalidArgumentForFunction".  Instead I get a java.lang.IllegalStateException "No source location found on PartiqlAst: {$static_type=int}".

A minimal test case (using the test framework in StaticTypeInferenceVisitorTransformTest:

    @Test
    fun `test function of struct reference with wrong type`() {
        val tc = TestCase(
            name = "STRUCT REFERENCE WITH WRONG TYPE",
            originalSql = "SELECT upper(structCol.field) as foo from a",
            globals = mapOf(
                "a" to BagType(StructType(mapOf("structCol" to StructType(mapOf("field" to INT)))))
            ),
            // This is wrong, but doesn't interfere with reproducing the problem
            handler = expectQueryOutputType(BagType(StructType(mapOf("foo" to STRING))))
        )
        runTest(tc)
    }

This is the exception stack:

java.lang.IllegalStateException: No source location found on PartiqlAst: {$static_type=int}

	at org.partiql.lang.eval.visitors.StaticTypeInferenceVisitorTransform$VisitorTransform.getSourceLocation(StaticTypeInferenceVisitorTransform.kt:111)
	at org.partiql.lang.eval.visitors.StaticTypeInferenceVisitorTransform$VisitorTransform.functionHasValidArgTypes(StaticTypeInferenceVisitorTransform.kt:902)
	at org.partiql.lang.eval.visitors.StaticTypeInferenceVisitorTransform$VisitorTransform.returnTypeForPropagatingFunction(StaticTypeInferenceVisitorTransform.kt:933)
	at org.partiql.lang.eval.visitors.StaticTypeInferenceVisitorTransform$VisitorTransform.computeReturnTypeForFunctionCall(StaticTypeInferenceVisitorTransform.kt:862)
	at org.partiql.lang.eval.visitors.StaticTypeInferenceVisitorTransform$VisitorTransform.transformExprCall(StaticTypeInferenceVisitorTransform.kt:489)
	at org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformExpr(partiql-domains.kt:15577)
	at org.partiql.lang.eval.visitors.VisitorTransformBase.transformExpr(VisitorTransformBase.kt:18)
	at org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformProjectItemProjectExpr_expr(partiql-domains.kt:16891)
	at org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformProjectItemProjectExpr(partiql-domains.kt:16873)
	at org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformProjectItem(partiql-domains.kt:16848)
	at org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformProjectionProjectList_projectItems(partiql-domains.kt:16791)
	at org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformProjectionProjectList(partiql-domains.kt:16776)
	at org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformProjection(partiql-domains.kt:16754)
	at org.partiql.lang.eval.visitors.StaticTypeInferenceVisitorTransform$VisitorTransform.transformProjection(StaticTypeInferenceVisitorTransform.kt:1519)
	at org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformExprSelect_project(partiql-domains.kt:16663)
	at org.partiql.lang.eval.visitors.VisitorTransformBase.transformExprSelectEvaluationOrder(VisitorTransformBase.kt:44)
	at org.partiql.lang.eval.visitors.StaticTypeInferenceVisitorTransform$VisitorTransform.transformExprSelect(StaticTypeInferenceVisitorTransform.kt:1569)
	at org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformExpr(partiql-domains.kt:15584)
	at org.partiql.lang.eval.visitors.VisitorTransformBase.transformExpr(VisitorTransformBase.kt:18)
	at org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformStatementQuery_expr(partiql-domains.kt:15448)
	at org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformStatementQuery(partiql-domains.kt:15433)
	at org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformStatement(partiql-domains.kt:15426)
	at org.partiql.lang.eval.visitors.StaticTypeInferenceVisitorTransform.transformStatement(StaticTypeInferenceVisitorTransform.kt:1595)
	at org.partiql.lang.ast.passes.inference.StaticTypeInferencer.inferStaticType(StaticTypeInferencer.kt:46)
	at org.partiql.lang.eval.visitors.StaticTypeInferenceVisitorTransformTest.runTest(StaticTypeInferenceVisitorTransformTest.kt:235)
	at org.partiql.lang.eval.visitors.StaticTypeInferenceVisitorTransformTest.test function of struct reference with wrong type(StaticTypeInferenceVisitorTransformTest.kt:88)

**Comment by lziq** [comment]
This error happens because, as an AST node, the type `PartiqlAst.Expr.Path` has no source location meta when getting transform from `ParseNode` to PIG AST. We can fix this bug by using the source location of its root AST node as its own source location.
