### ISSUE TITLE
PartialEvaluationRewriter and PreventJoinVisitor examples cannot be run

### ISSUE THREAD

**Issue by arun-gupta** [partiql/partiql-lang-kotlin#70]
A couple of samples are failing:

```
partiql-lang-kotlin $ ./gradlew :examples:run -q --args="PartialEvaluationRewriter"
Exception in thread "main" java.lang.RuntimeException: unknown example name: PartialEvaluationRewriter
        at org.partiql.examples.util.Main.main(Main.kt:35)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':examples:run'.
> Process 'command '/Users/argu/.sdkman/candidates/java/8.0.202-amzn/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
partiql-lang-kotlin $ ./gradlew :examples:run -q --args="PreventJoinVisitor"
Exception in thread "main" java.lang.RuntimeException: unknown example name: PreventJoinVisitor
        at org.partiql.examples.util.Main.main(Main.kt:35)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':examples:run'.
> Process 'command '/Users/argu/.sdkman/candidates/java/8.0.202-amzn/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by therapon** [comment]
The invocations are missing the suffix `Example`., e.g. .
* `/gradlew :examples:run --args="PreventJoinVisitorExample"` not  
* `./gradlew :examples:run --args="PreventJoinVisitor"

Both worked for me 

```
/gradlew :examples:run --args="PartialEvaluationRewriterExample"
> Task :lang:compileKotlin UP-TO-DATE
> Task :lang:compileJava NO-SOURCE
> Task :examples:compileKotlin UP-TO-DATE
> Task :examples:compileJava UP-TO-DATE
> Task :examples:processResources NO-SOURCE
> Task :examples:classes UP-TO-DATE
> Task :lang:processResources NO-SOURCE
> Task :lang:classes UP-TO-DATE
> Task :lang:inspectClassesForKotlinIC UP-TO-DATE
> Task :lang:jar UP-TO-DATE

> Task :examples:run
Running example: PartialEvaluationRewriterExample
Original AST:
    (ast (version 1) (root (term (exp (+ (term (exp (lit 1)) (meta ($source_location ({line_num:1,char_offset:1})))) (term (exp (lit 1)) (meta ($source_location ({line_num:1,char_offset:5})))))) (meta ($source_location ({line_num:1,char_offset:3}))))))
Rewritten AST:
    (ast (version 1) (root (term (exp (lit 2)) (meta ($source_location ({line_num:1,char_offset:3}))))))
End of example: PartialEvaluationRewriterExample


BUILD SUCCESSFUL in 1s
6 actionable tasks: 1 executed, 5 up-to-date



> ./gradlew :examples:run --args="PreventJoinVisitorExample"   [~/Github/partiql-lang-kotlin]
> Task :lang:compileKotlin UP-TO-DATE
> Task :lang:compileJava NO-SOURCE
> Task :examples:compileKotlin UP-TO-DATE
> Task :examples:compileJava UP-TO-DATE
> Task :examples:processResources NO-SOURCE
> Task :examples:classes UP-TO-DATE
> Task :lang:processResources NO-SOURCE
> Task :lang:classes UP-TO-DATE
> Task :lang:inspectClassesForKotlinIC UP-TO-DATE
> Task :lang:jar UP-TO-DATE

> Task :examples:run
Running example: PreventJoinVisitorExample
PartiQL query without JOINs:
    SELECT foo FROM bar
Has joins:
    false
PartiQL query with JOINs:
    SELECT foo FROM bar CROSS JOIN bat
Has joins:
    true
End of example: PreventJoinVisitorExample


BUILD SUCCESSFUL in 1s
6 actionable tasks: 1 executed, 5 up-to-date

```
