### ISSUE TITLE
PartiQL Should Be Able to Cast Very Small Decimal to Integer

### ISSUE THREAD

**Issue by lziq** [partiql/partiql-lang-kotlin#784]
## Description
- When casting small enough decimal values to integer, PartiQL throws error improperly. 

## To Reproduce
```
    val ion = IonSystemBuilder.standard().build()
    val pipeline = CompilerPipeline
        .builder(ion)
        .compileOptions(
            CompileOptions.build {
                typedOpBehavior(TypedOpBehavior.HONOR_PARAMETERS)
            }
        )
        .build()
    val e = pipeline.compile("cast(1e-2147483609 as int)")
    val result = e.eval(EvaluationSession.standard())

    println(result)
```

The error is: 
```
Exception in thread "main" org.partiql.lang.eval.EvaluationException: Internal error, BigInteger would overflow supported range
	Evaluator Error: at line 1, column 1: Generic exception, <UNKNOWN> : <UNKNOWN>

	at org.partiql.lang.eval.ThunkKt$DEFAULT_EXCEPTION_HANDLER_FOR_LEGACY_MODE$1.invoke(Thunk.kt:111)
	at org.partiql.lang.eval.ThunkKt$DEFAULT_EXCEPTION_HANDLER_FOR_LEGACY_MODE$1.invoke(Thunk.kt)
	at org.partiql.lang.eval.LegacyThunkFactory.handleException(Thunk.kt:558)
	at org.partiql.lang.eval.ThunkFactory$thunkEnv$1.invoke(Thunk.kt:218)
	at org.partiql.lang.eval.ThunkFactory$thunkEnv$1.invoke(Thunk.kt:137)
	at org.partiql.lang.eval.EvaluatingCompiler$compile$1.eval(EvaluatingCompiler.kt:336)
	at org.partiql.lang.TestKt.main(test.kt:19)
	at org.partiql.lang.TestKt.main(test.kt)
```

## Expected Behavior
It should be 0

**Comment by Neha261289** [comment]
Can i work on this issue. This is my first time working on this project. Would this be a good first issue to work on?

**Comment by lziq** [comment]
I think it's a good first issue and you are more than welcome to contribute. The root cause of is this line, https://github.com/partiql/partiql-lang-kotlin/blob/main/lang/src/org/partiql/lang/eval/ExprValueExtensions.kt#L348. See if you can fix it?
