### ISSUE TITLE
Indeterministic error during build process

### ISSUE THREAD

**Issue by yliuuuu** [partiql/partiql-lang-kotlin#951]
## Description
- During local build, we sometimes receive an indeterministic error message with the following format: 
```
[Test Case]
Caused by:
 org.partiql.lang.eval.EvaluationException: Variable not in GROUP BY or aggregation function: [variable name]
```
The test case showing may change from time to time but the error message is largely consistent. The problem may get fixed by running build command again or clean Gradle cache. 
- I am not aware if the same error ever appear during Github workflow build. 

A full example: 
```
TrimEvaluationTest > runPassTests(ExprFunctionTestCase) > org.partiql.lang.eval.builtins.functions.TrimEvaluationTest.runPassTests(ExprFunctionTestCase)[27] FAILED
    org.partiql.lang.eval.evaluatortestframework.EvaluatorAssertionFailedError: Failure reason: FAILED_TO_EVALUATE_QUERY
    Note            : PartiQLCompilerPipeline (compile options unaltered)
    Group name      : null
    Query           : SELECT trim(both el from '   1ab1  ') AS trimmed
    FROM <<' 1'>> AS el
    Target pipeline : ALL_PIPELINES
    Expected result : [{trimmed:"ab"}]
    Actual result   : null
    Result format   : ION_WITHOUT_BAG_AND_MISSING_ANNOTATIONS
        at app//org.partiql.lang.eval.evaluatortestframework.AssertionsKt.assertDoesNotThrow(Assertions.kt:24)
        at app//org.partiql.lang.eval.evaluatortestframework.PipelineEvaluatorTestAdapter.privateRunEvaluatorTestCase(PipelineEvaluatorTestAdapter.kt:55)
        at app//org.partiql.lang.eval.evaluatortestframework.PipelineEvaluatorTestAdapter.runEvaluatorTestCase(PipelineEvaluatorTestAdapter.kt:28)
        at app//org.partiql.lang.eval.evaluatortestframework.MultipleTestAdapter.runEvaluatorTestCase(MultipleTestAdapter.kt:10)
        at app//org.partiql.lang.eval.EvaluatorTestBase.runEvaluatorTestCase(EvaluatorTestBase.kt:88)
        at app//org.partiql.lang.eval.EvaluatorTestBase.runEvaluatorTestCase$default(EvaluatorTestBase.kt:75)
        at app//org.partiql.lang.eval.builtins.functions.TrimEvaluationTest.runPassTests(TrimEvaluationTest.kt:22)
        Caused by:
        org.partiql.lang.eval.EvaluationException: Variable not in GROUP BY or aggregation function: el
            Evaluator Error: at line 1, column 18: Variable 'el' must appear in the GROUP BY clause or be used in an aggregation function
            at app//org.partiql.lang.eval.visitors.AggregationVisitorTransform$GroupKeyReferenceTransformer.getReplacementForIdOutsideOfAggregationFunction(AggregationVisitorTransform.kt:291)
            at app//org.partiql.lang.eval.visitors.AggregationVisitorTransform$GroupKeyReferenceTransformer.transformExprId(AggregationVisitorTransform.kt:240)
            at app//org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformExpr(PartiqlAst.generated.kt:18308)
            at app//org.partiql.lang.eval.visitors.VisitorTransformBase.transformExpr(VisitorTransformBase.kt:18)
            at app//org.partiql.lang.eval.visitors.AggregationVisitorTransform$GroupKeyReferenceTransformer.transformExpr(AggregationVisitorTransform.kt:258)
            at app//org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformExprCall_args(PartiqlAst.generated.kt:19205)
            at app//org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformExprCall(PartiqlAst.generated.kt:19186)
            at app//org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformExpr(PartiqlAst.generated.kt:18342)
            at app//org.partiql.lang.eval.visitors.VisitorTransformBase.transformExpr(VisitorTransformBase.kt:18)
            at app//org.partiql.lang.eval.visitors.AggregationVisitorTransform$GroupKeyReferenceTransformer.transformExpr(AggregationVisitorTransform.kt:258)
            at app//org.partiql.lang.eval.visitors.AggregationVisitorTransform$transformProjectionProjectList$1.invoke(AggregationVisitorTransform.kt:190)
            at app//org.partiql.lang.eval.visitors.AggregationVisitorTransform$transformProjectionProjectList$1.invoke(AggregationVisitorTransform.kt:88)
            at app//org.partiql.lang.domains.PartiqlAst$Companion.build(PartiqlAst.generated.kt:25)
            at app//org.partiql.lang.eval.visitors.AggregationVisitorTransform.transformProjectionProjectList(AggregationVisitorTransform.kt:177)
            at app//org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformProjection(PartiqlAst.generated.kt:19535)
            at app//org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformExprSelect_project(PartiqlAst.generated.kt:19442)
            at app//org.partiql.lang.eval.visitors.VisitorTransformBase.transformExprSelectEvaluationOrder(VisitorTransformBase.kt:45)
            at app//org.partiql.lang.eval.visitors.AggregationVisitorTransform.transformExprSelect(AggregationVisitorTransform.kt:103)
            at app//org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformExpr(PartiqlAst.generated.kt:18350)
            at app//org.partiql.lang.eval.visitors.VisitorTransformBase.transformExpr(VisitorTransformBase.kt:18)
            at app//org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformStatementQuery_expr(PartiqlAst.generated.kt:18155)
            at app//org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformStatementQuery(PartiqlAst.generated.kt:18140)
            at app//org.partiql.lang.domains.PartiqlAst$VisitorTransform.transformStatement(PartiqlAst.generated.kt:18132)
            at app//org.partiql.lang.eval.visitors.PipelinedVisitorTransform.transformStatement(PipelinedVisitorTransform.kt:17)
            at app//org.partiql.lang.planner.PartiQLPlannerDefault.normalize(PartiQLPlannerDefault.kt:130)
            at app//org.partiql.lang.planner.PartiQLPlannerDefault.access$normalize(PartiQLPlannerDefault.kt:41)
            at app//org.partiql.lang.planner.PartiQLPlannerDefault.plan(PartiQLPlannerDefault.kt:54)
            at app//org.partiql.lang.compiler.PartiQLCompilerPipeline.compile(PartiQLCompilerPipeline.kt:101)
            at app//org.partiql.lang.compiler.PartiQLCompilerPipeline.compile(PartiQLCompilerPipeline.kt:94)
            at app//org.partiql.lang.eval.evaluatortestframework.PartiQLCompilerPipelineFactory$createPipeline$1.evaluate(PartiQLCompilerPipelineFactory.kt:96)
            at app//org.partiql.lang.eval.evaluatortestframework.PipelineEvaluatorTestAdapter$privateRunEvaluatorTestCase$actualExprValueResult$2.invoke(PipelineEvaluatorTestAdapter.kt:59)
            at app//org.partiql.lang.eval.evaluatortestframework.PipelineEvaluatorTestAdapter$privateRunEvaluatorTestCase$actualExprValueResult$2.invoke(PipelineEvaluatorTestAdapter.kt:15)
            at app//org.partiql.lang.eval.evaluatortestframework.AssertionsKt.assertDoesNotThrow(Assertions.kt:22)
            ... 6 more

```

## To Reproduce
- `./gredlew build`
Note the error appears to be indeterministic, i.e., it may or may not appears when build. The exact cause is yet to be found. 

## Expected Behavior
- Local build consistently success.

**Comment by RCHowell** [comment]
I'm seeing the same thing locally. It's a different test each time. 

```
EvaluatingCompilerUnknownValuesTest > testUnknownPropagation(EvaluatorTestCase) > org.partiql.lang.eval.EvaluatingCompilerUnknownValuesTest.testUnknownPropagation(EvaluatorTestCase)[153] FAILED
    org.partiql.lang.eval.evaluatortestframework.EvaluatorAssertionFailedError: Failure reason: FAILED_TO_EVALUATE_QUERY
    Note            : PartiQLCompilerPipeline (compile options unaltered)
    Group name      : BETWEEN : LEGACY
    Query           : SELECT i.x BETWEEN i.y AND i.z AS result FROM << { 'x': MISSING, 'y': 1, 'z': 3 } >> AS i
    Target pipeline : ALL_PIPELINES
    Expected result : << { 'result': null } >>
    Actual result   : null
    Result format   : STRICT
        at app//org.partiql.lang.eval.evaluatortestframework.AssertionsKt.assertDoesNotThrow(Assertions.kt:24)
        at app//org.partiql.lang.eval.evaluatortestframework.PipelineEvaluatorTestAdapter.privateRunEvaluatorTestCase(PipelineEvaluatorTestAdapter.kt:54)
        at app//org.partiql.lang.eval.evaluatortestframework.PipelineEvaluatorTestAdapter.runEvaluatorTestCase(PipelineEvaluatorTestAdapter.kt:27)
        at app//org.partiql.lang.eval.evaluatortestframework.MultipleTestAdapter.runEvaluatorTestCase(MultipleTestAdapter.kt:10)
        at app//org.partiql.lang.eval.EvaluatorTestBase.runEvaluatorTestCase(EvaluatorTestBase.kt:99)
        at app//org.partiql.lang.eval.EvaluatingCompilerUnknownValuesTest.testUnknownPropagation(EvaluatingCompilerUnknownValuesTest.kt:49)

        Caused by:
        org.partiql.lang.eval.EvaluationException: Variable not in GROUP BY or aggregation function: i
                Evaluator Error: at line 1, column 8: Variable 'i' must appear in the GROUP BY clause or be used in an aggregation function
....
```

Need to look at this now because I can't build locally

**Comment by RCHowell** [comment]
Looks like it was the result of using an Object class - which becomes a Java static final class. We shouldn't keep state in a  static class

Here's the fix
```
// before
private object AggregationFinder : PartiqlAst.Visitor() {

// fixed
private class AggregationFinder : PartiqlAst.Visitor() {
```
